### ISSUE TITLE
Communication with RabbitMQ not working

### ISSUE THREAD

**Issue by jeandemeusy** [hoprnet/ct-applications#4]
Following the [README.md](https://github.com/hoprnet/ct-applications/blob/main/staging/rabbitmq/README.md) provided for testing the broker, I can't make it work.

```bash

$ kubectl logs -f -n ${ENVIRONMENT_NAME} perf-test

Main thread caught exception: java.lang.NullPointerException: Cannot invoke "String.toLowerCase()" because the return value of "java.net.URI.getScheme()" is null
07:31:49.431 [main] ERROR com.rabbitmq.perf.PerfTest - Main thread caught exception
java.lang.NullPointerException: Cannot invoke "String.toLowerCase()" because the return value of "java.net.URI.getScheme()" is null
        at com.rabbitmq.client.ConnectionFactory.setUri(ConnectionFactory.java:313)
        at com.rabbitmq.client.ConnectionFactory.setUri(ConnectionFactory.java:380)
        at com.rabbitmq.perf.PerfTest.main(PerfTest.java:303)
        at com.rabbitmq.perf.PerfTest.main(PerfTest.java:604)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:108)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:65)
```

I tried to look at the host and ping it directly to check it's status, but both the commands
```bash
$ ping rabbitmq-ha-cluster.rabbitmq.svc
```
or

```bash
$ host rabbitmq-ha-cluster.rabbitmq.svc
```

are telling me that the host is not reachable.

**Comment by jeandemeusy** [comment]
The missing piece of information was that the host was accessible only on cluster, not locally. A simple port-forwarding provided by @sitilge fixed the issue.

```bash
kubectl -n rabbitmq port-forward svc/rabbitmq-ha-cluster 5672:5672
```
